version: 32
jobs:
- name: Terraform Apply
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Terraform
    runInContainer: true
    image: ubuntu:rolling
    interpreter: !DefaultInterpreter
      commands: |
        snap install --classic opentofu
        tofu init
        tofu plan
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
